name: Main Branch CI

run-name: "📦 Main Branch CI"

on:
  push:
    branches:
      - main
    paths:
      - app/**
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  GHCR_REPOSITORY_NAME: "decenter-sre"
  NERDCTL_VERSION: "2.1.3"
  SOCI_SNAPSHOTTER_VERSION: "0.12.1"
  BUILDKIT_VERSION: "v0.27.1"

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Image Metadata
        id: meta
        run: |
          GHCR_REPOSITORY="ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/${{ env.GHCR_REPOSITORY_NAME }}"
          SHORT_SHA="${GITHUB_SHA:0:7}"
          echo "ghcr_repository=${GHCR_REPOSITORY}" >> $GITHUB_OUTPUT
          echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Install nerdctl
        run: |
          wget "https://github.com/containerd/nerdctl/releases/download/v${NERDCTL_VERSION}/nerdctl-${NERDCTL_VERSION}-linux-amd64.tar.gz"
          tar -xzf nerdctl-${NERDCTL_VERSION}-linux-amd64.tar.gz nerdctl
          sudo mv nerdctl /usr/bin/nerdctl
          rm nerdctl-${NERDCTL_VERSION}-linux-amd64.tar.gz
          nerdctl --version

      - name: Install SOCI snapshotter
        run: |
          wget "https://github.com/awslabs/soci-snapshotter/releases/download/v${SOCI_SNAPSHOTTER_VERSION}/soci-snapshotter-${SOCI_SNAPSHOTTER_VERSION}-linux-amd64.tar.gz"
          sudo tar -C /usr/local/bin -xvf soci-snapshotter-${SOCI_SNAPSHOTTER_VERSION}-linux-amd64.tar.gz soci soci-snapshotter-grpc
          rm soci-snapshotter-${SOCI_SNAPSHOTTER_VERSION}-linux-amd64.tar.gz
          soci --version

      - name: Install BuildKit
        run: |
          wget "https://github.com/moby/buildkit/releases/download/${BUILDKIT_VERSION}/buildkit-${BUILDKIT_VERSION}.linux-amd64.tar.gz"
          tar -xzf "buildkit-${BUILDKIT_VERSION}.linux-amd64.tar.gz"
          sudo mv bin/buildctl /usr/local/bin/
          sudo mv bin/buildkitd /usr/local/bin/
          sudo chmod +x /usr/local/bin/buildctl /usr/local/bin/buildkitd
          (sudo buildkitd > /dev/null 2>&1 &)
          sleep 5
          sudo buildctl debug workers    
          buildctl --version
          buildkitd --version

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | sudo nerdctl login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build image
        run: |
          sudo -E nerdctl build -f ./app/Dockerfile -t temp-img:default ./app
          sudo nerdctl image convert --soci temp-img:default --oci temp-img:soci
          sudo nerdctl tag temp-img:soci ${{ steps.meta.outputs.ghcr_repository }}:${{ steps.meta.outputs.short_sha }}
          sudo nerdctl tag temp-img:soci ${{ steps.meta.outputs.ghcr_repository }}:latest
          sudo nerdctl push ${{ steps.meta.outputs.ghcr_repository }}:${{ steps.meta.outputs.short_sha }}
          sudo nerdctl push ${{ steps.meta.outputs.ghcr_repository }}:latest

      - name: CI summary
        run: |
          echo "📦 CI Summary"
          echo "===================="
          echo "Commit SHA: ${{ github.sha }}"
          echo "Short SHA: ${{ steps.meta.outputs.short_sha }}"
          echo "Image: ${{ steps.meta.outputs.ghcr_repository }}:${{ steps.meta.outputs.short_sha }} and ${{ steps.meta.outputs.ghcr_repository }}:latest"
          echo "===================="
